//! Contract test: the engine must render exactly what the Laravel backend emits.
//!
//! `tools/reference.json` is generated by importing the original TypeScript library
//! and dumping every arranged track, and `php tools/compare-with-original.php`
//! asserts the PHP `Library` produces the same JSON. This test closes the loop: it
//! feeds that same JSON to `bckgrnd_msc_engine::Track` and renders each track, so a
//! mismatch in the PHP↔WASM contract fails here rather than as silence in the app.

use std::collections::BTreeMap;

use bckgrnd_msc_engine::{Engine, NoteEvent, Stem, Track, TrackKind, STEPS};

fn reference_path() -> String {
    format!("{}/../tools/reference.json", env!("CARGO_MANIFEST_DIR"))
}

fn load_reference() -> BTreeMap<String, Track> {
    let raw =
        std::fs::read_to_string(reference_path()).unwrap_or_else(|e| panic!("read reference: {e}"));
    serde_json::from_str(&raw).expect("reference.json must deserialize as tracks")
}

#[test]
fn every_backend_track_deserializes() {
    let tracks = load_reference();
    assert_eq!(tracks.len(), 12, "the library should have twelve tracks");

    for (id, track) in &tracks {
        assert_eq!(&track.id, id, "map key should match the track id");
        for stem in Stem::ALL {
            assert!(
                track.mix.get(stem) > 0.0 && track.mix.get(stem) <= 1.0,
                "{id}: {} fader out of range: {}",
                stem.as_str(),
                track.mix.get(stem)
            );
        }
        for lane in [&track.kick, &track.clap, &track.hat, &track.hat_open] {
            assert_eq!(lane.len(), STEPS, "{id}: drum lanes are 256 steps");
        }
        for lane in [
            &track.bass,
            &track.stab,
            &track.lead,
            &track.pad,
            &track.arp,
        ] {
            assert_eq!(lane.len(), STEPS, "{id}: note lanes are 256 steps");
        }
        assert!(track.bpm > 0.0, "{id}: needs a tempo");
    }
}

#[test]
fn every_backend_track_is_playable_and_silent_at_its_edges() {
    for (id, track) in load_reference() {
        let mut engine = Engine::new(48_000.0);
        engine.load_track(track);
        assert!(!engine.is_playing());

        engine.play();
        assert!(engine.is_playing(), "{id}: should start");

        // Render four bars' worth of audio, checking every sample.
        let mut peak = 0.0f32;
        let mut blocks = 0;
        while blocks < 600 {
            let mut left = [0.0f32; 128];
            let mut right = [0.0f32; 128];
            engine.process(&mut left, &mut right);
            for (l, r) in left.iter().zip(right.iter()) {
                assert!(l.is_finite() && r.is_finite(), "{id}: non-finite output");
                peak = peak.max(l.abs()).max(r.abs());
            }
            blocks += 1;
        }
        assert!(peak > 0.05, "{id}: rendered silence (peak {peak})");
        assert!(peak <= 1.5, "{id}: ran away (peak {peak})");
    }
}

#[test]
fn backend_tracks_keep_their_flavour() {
    let tracks = load_reference();

    // The 303 is the only acid track, and acid must sound different: heavier bass
    // fader, no swing, and a bassline with accents for the resonant sweep to key on.
    let acid = &tracks["acid"];
    assert_eq!(acid.kind, TrackKind::Acid);
    assert_eq!(acid.swing, 0.0);
    assert!((acid.mix.get(Stem::Bass) - 0.9).abs() < 1e-6);
    assert!(
        acid.bass
            .iter()
            .filter_map(|e| e.as_ref())
            .any(|e| e.accent),
        "acid needs accented notes for the sweep"
    );

    // Lo-fi tracks sit slower and swing harder.
    for (id, track) in &tracks {
        if track.kind == TrackKind::Lofi {
            assert!(
                track.bpm < 100.0,
                "{id}: lo-fi should be slow, got {}",
                track.bpm
            );
            assert!(track.swing > 0.3, "{id}: lo-fi should swing");
        }
    }

    // Four on the floor: a kick on every beat of the groove section.
    let warehouse = &tracks["warehouse"];
    assert_eq!(warehouse.kind, TrackKind::House);
    for bar in 4..8 {
        for beat in [0usize, 4, 8, 12] {
            assert!(
                warehouse.kick[bar * 16 + beat] > 0.0,
                "warehouse groove bar {bar} beat {beat} should have a kick"
            );
        }
    }
}

#[test]
fn song_form_is_present_in_the_arrangement() {
    let tracks = load_reference();

    // The intro holds the chords back: stabs and arp are silent in bars 0-1 and
    // arrive in the drop, which is what makes the arrangement read as a build.
    let track = &tracks["warehouse"];
    let has_stab = |bar: usize| {
        track.stab[bar * 16..(bar + 1) * 16]
            .iter()
            .any(|e| e.is_some())
    };

    assert!(!has_stab(0), "intro should withhold the chords");
    assert!(has_stab(4), "groove should have them");
    assert!(has_stab(12), "drop should have them");

    // The break drops the clap entirely.
    let clap_in_break = track.clap[8 * 16..12 * 16].iter().any(|v| *v > 0.0);
    assert!(!clap_in_break, "the break should drop the clap");
}

#[test]
fn a_loaded_track_drives_the_engine_controls() {
    let tracks = load_reference();
    let mut engine = Engine::new(48_000.0);
    engine.load_track(tracks["tunnel"].clone());

    // Tempo, swing and loop all come from the arrangement, not from defaults.
    assert_eq!(engine.track().bpm, 128.0);
    engine.set_loop(2);
    engine.set_bpm(140.0);

    engine.play();
    for _ in 0..200 {
        let mut left = [0.0f32; 128];
        let mut right = [0.0f32; 128];
        engine.process(&mut left, &mut right);
    }

    assert!(
        engine.visual_step() >= 0,
        "playhead should advance while playing"
    );
    assert!(
        engine.levels().iter().any(|l| *l > 0.0),
        "meters should show signal"
    );
}

#[test]
fn muting_a_stem_on_a_real_track_silences_it() {
    let tracks = load_reference();
    let mut engine = Engine::new(48_000.0);
    engine.load_track(tracks["basement"].clone());

    // Cut every drum stem, then confirm only the melodic content is left.
    for stem in [Stem::Kick, Stem::Clap, Stem::Hats] {
        engine.set_muted(stem, true);
    }
    engine.play();
    let mut peak = 0.0f32;
    for _ in 0..200 {
        let mut left = [0.0f32; 128];
        let mut right = [0.0f32; 128];
        engine.process(&mut left, &mut right);
        peak = peak.max(left.iter().fold(0.0f32, |m, v| m.max(v.abs())));
    }
    assert!(peak > 0.0, "the melodic stems should still sound");

    // Now cut those too. The delay line is fed post-fader by the stems, so no new
    // material enters it, but what is already ringing keeps ringing — which is the
    // point of a stem mixer: cutting the drums leaves the echo, it does not kill it.
    for stem in Stem::TUNED {
        engine.set_muted(stem, true);
    }
    let mut tail = 0.0f32;
    for _ in 0..400 {
        let mut left = [0.0f32; 128];
        let mut right = [0.0f32; 128];
        engine.process(&mut left, &mut right);
        tail = tail.max(left.iter().fold(0.0f32, |m, v| m.max(v.abs())));
    }
    assert!(
        tail < 0.2,
        "the tail should be well under the direct sound, got {tail}"
    );
    // And it decays to nothing, rather than feeding back forever.
    for _ in 0..600 {
        let mut left = [0.0f32; 128];
        let mut right = [0.0f32; 128];
        engine.process(&mut left, &mut right);
        assert!(
            left.iter().all(|v| v.abs() < 1e-6),
            "with every stem cut the tail must decay away"
        );
    }
}

#[test]
fn note_events_carry_pitches_from_the_library() {
    let tracks = load_reference();

    // The warehouse pad opens on an A minor 7 voicing: A3 C4 E4 G4.
    let pad = tracks["warehouse"].pad[0]
        .as_ref()
        .expect("the pad should start on step 0");
    assert_eq!(
        pad.notes,
        vec![57.0, 60.0, 64.0, 67.0],
        "expected A3 C4 E4 G4"
    );

    // The acid bass sits around A2 with chromatic movement.
    let acid = &tracks["acid"];
    let pitches: Vec<i32> = acid
        .bass
        .iter()
        .filter_map(|e| e.as_ref())
        .map(|e| e.first(0.0) as i32)
        .collect();
    assert!(!pitches.is_empty());
    assert!(
        pitches.iter().all(|p| (33..=64).contains(p)),
        "acid bass should stay low: {pitches:?}"
    );

    // Accents must survive the round trip.
    let accented = acid
        .bass
        .iter()
        .filter(|e| e.as_ref().is_some_and(|n: &NoteEvent| n.accent))
        .count();
    assert!(
        accented > 20,
        "expected a heavily accented acid line, got {accented}"
    );
}
